### ISSUE TITLE
keypath not working

### ISSUE THREAD

**Issue by Sigfried** [jacobflanagan/nesteddictionary#1]
Shouldn't this work?

    In [75]: from nesteddictionary import NestedDict

    In [76]: d = NestedDict()

    In [77]: d[[1,2,3]] = 'a'
    ---------------------------------------------------------------------------
    KeyError                                  Traceback (most recent call last)
    <ipython-input-77-9879dca6206c> in <module>
    ----> 1 d[[1,2,3]] = 'a'

    c:\users\sigfried\appdata\local\programs\python\python37-32\lib\site-packages\nesteddictionary\__init__.py in __setitem__(self, keypath, value)
        175         if isinstance(keypath,list):
        176             journeykeys, destinationkey = keypath[:-1], keypath[-1]
    --> 177             self._traverse(journeykeys)[destinationkey] = value
        178         else:
        179             self._data[keypath] = value

    c:\users\sigfried\appdata\local\programs\python\python37-32\lib\site-packages\nesteddictionary\__init__.py in _traverse(self, keypath, construct_path)
        109
        110         if isinstance(keypath, list):
    --> 111             return reduce(operator.getitem, keypath, self._data)
        112         else:
        113             return self._data[keypath]

    KeyError: 1

**Comment by Sigfried** [comment]
Never mind. I found this one: https://github.com/bunbun/nested-dict

**Comment by Sigfried** [comment]
That one doesn't have keypaths I don't think... oh well

**Comment by Sigfried** [comment]
Looks like pydash has what I want: https://pydash.readthedocs.io/en/latest/api.html#module-pydash.objects

**Comment by mortowsic** [comment]
Please remove the print from line 160 in the get() function

**Comment by jacobflanagan** [comment]
Very late reply... That is an intriguing method for inserting values (very straightforward). However, this functionality is available using the insert method:

> `nested_dict.insert( [1,2,3], 'a' )`

This library is somewhat specific so I won't build out this functionality unless there's more of an interest.
